image:
  curl: badouralix/curl-jq-yq:ubuntu
url_to_test: https://www.google.fr
curlOption: "-k"
command: sh /scripts/kubernetescurljob.sh
secret:
  proxy:
    mount: mi-serviceteam
    path: orion-creds
useProxy: true
proxy_host: proxymi
proxy_port: 8888
configMap:
  name: st-test-nginx-config
url_to_test_mi: http://demo-cpin-ines.d650.dev.forge.minint.fr
